name: mikan_flutter
description: mikanani.me

version: 1.0.0-RC33+55

publish_to: none

environment:
  sdk: ">=2.16.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.4
  firebase_crashlytics: ^2.8.10
  path_provider: ^2.0.11
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  provider: ^6.0.3
  oktoast: ^3.3.0
  pull_to_refresh: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0
  fluentui_system_icons: ^1.1.180
  clipboard: ^0.1.3
  url_launcher: ^6.1.5
  share_plus: ^4.1.0
  flutter_widget_from_html_core: ^0.8.5+3
  extended_sliver: ^2.1.3
  waterfall_flow: ^3.0.2
  modal_bottom_sheet: ^2.1.2
  jiffy: ^5.0.0
  android_intent_plus: ^3.1.1+1
  isolate: ^2.1.1
  connectivity_plus: ^2.3.6+1
  ff_annotation_route_core: ^2.0.4
  ff_annotation_route_library: ^3.0.0
  sprung: ^3.0.1
  sliver_tools: ^0.2.8
  bitsdojo_window: ^0.1.5
  flutter_displaymode: ^0.4.0
  infinite_carousel: ^1.0.2
  flex_color_picker: ^2.6.1
  intl: ^0.17.0
  collection: ^1.16.0
  json_annotation: ^4.6.0
  path: ^1.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.3.1
  yaml: ^3.1.1
  glob: ^2.1.0
  http: ^0.13.5
  process_run: ^0.12.3+2
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.5
  quiver: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: mono
      fonts:
        - asset: assets/fonts/mono/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/mono/JetBrainsMono-Italic.ttf
        - asset: assets/fonts/mono/JetBrainsMono-Medium.ttf
        - asset: assets/fonts/mono/JetBrainsMono-Medium-Italic.ttf
        - asset: assets/fonts/mono/JetBrainsMono-Bold.ttf
        - asset: assets/fonts/mono/JetBrainsMono-Bold-Italic.ttf
        - asset: assets/fonts/mono/JetBrainsMono-ExtraBold.ttf
        - asset: assets/fonts/mono/JetBrainsMono-ExtraBold-Italic.ttf


icons_launcher:
  image_path: 'assets/mikan.png'
  platforms:
    android:
      enable: false
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

